# Generated by Django 3.1.5 on 2021-01-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sending_time', models.DateTimeField(blank=True, null=True, verbose_name='Sending time')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('message_text', models.TextField(max_length=999, verbose_name='Message text')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
            },
        ),
    ]
