# Generated by Django 3.1.4 on 2020-12-15 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20201214_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollector',
            name='phone_num',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
