# Generated by Django 3.1.4 on 2020-12-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_emailcollector_phone_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcollector',
            name='department_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Department Name'),
            preserve_default=False,
        ),
    ]
