# Generated by Django 3.1.4 on 2020-12-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', editable=False, max_length=200, verbose_name='Category')),
                ('description', models.TextField(default='', editable=False, max_length=25, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', editable=False, max_length=200, verbose_name='Product name')),
                ('product_brand', models.CharField(default='', editable=False, max_length=200, verbose_name='Product brand')),
                ('year_of_manufacture', models.IntegerField(default='', editable=False, verbose_name='Year of manufacture')),
                ('color', models.CharField(default='', editable=False, max_length=25, verbose_name='Color')),
                ('description', models.TextField(default='', editable=False, max_length=25, verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products5_1.category', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products5_1.product', verbose_name='Good')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'db_table': 'products_categories',
            },
        ),
    ]
