# Generated by Django 3.1.4 on 2021-01-04 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='', editable=False, max_length=30, verbose_name='Category')),
                ('description', models.TextField(default='', max_length=999, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(default='', editable=False, verbose_name='Date entered')),
                ('password', models.CharField(default='', editable=False, max_length=25, verbose_name='Password')),
                ('birthday', models.DateField(default='', editable=False, verbose_name='Date of birth')),
                ('client_type', models.CharField(default='', editable=False, max_length=25, verbose_name='Client type')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(editable=False, max_length=60, verbose_name='Last name')),
                ('middle_name', models.CharField(editable=False, max_length=60, verbose_name='Middle name')),
                ('prefix_name', models.CharField(editable=False, max_length=10, verbose_name='Prefix name')),
                ('company_name', models.CharField(editable=False, max_length=80, verbose_name='Company name')),
                ('contact_type', models.CharField(editable=False, max_length=80, verbose_name='Contact type')),
                ('address', models.CharField(editable=False, max_length=200, verbose_name='Address')),
                ('city', models.CharField(editable=False, max_length=40, verbose_name='City')),
                ('state', models.CharField(editable=False, max_length=40, verbose_name='State')),
                ('country', models.CharField(editable=False, max_length=40, verbose_name='Country')),
                ('postal_code', models.CharField(editable=False, max_length=5, verbose_name='Postal code')),
                ('phone', models.CharField(editable=False, max_length=12, verbose_name='Phone')),
                ('email', models.EmailField(editable=False, max_length=30, verbose_name='Email')),
                ('create_time', models.DateField(editable=False, verbose_name='Creation time')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='', editable=False, max_length=50, verbose_name='Product name')),
                ('product_brand', models.CharField(default='', editable=False, max_length=40, verbose_name='Product brand')),
                ('year_of_manufacture', models.IntegerField(default=0, verbose_name='Year of manufacture')),
                ('color', models.CharField(default='', editable=False, max_length=25, verbose_name='Color')),
                ('description', models.TextField(default='', editable=False, max_length=999, verbose_name='Description')),
                ('quantity_per_unit', models.IntegerField(default=0, verbose_name='Quantity per unit')),
                ('unit_price', models.FloatField(default=0, editable=False, verbose_name='Unit price')),
                ('product_image', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Image of the product')),
                ('size', models.CharField(default='', max_length=25, verbose_name='Size x*y*z')),
                ('weight', models.FloatField(default=0, max_length=7, verbose_name='Weight of the product in KGs')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(editable=False, max_length=45, verbose_name='Contract number')),
                ('contract_title', models.CharField(editable=False, max_length=50, verbose_name='Contract title')),
                ('supplier_type', models.CharField(editable=False, max_length=40, verbose_name='Supplier type')),
                ('contr_eff_date', models.DateField(editable=False, verbose_name='Contract effective date')),
                ('contr_exp_date', models.DateField(editable=False, verbose_name='Contract expiration date')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products5_1.contact', verbose_name='Contact ID')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_no', models.CharField(editable=False, max_length=45, verbose_name='Contract number')),
                ('contract_title', models.CharField(editable=False, max_length=50, verbose_name='Contract title')),
                ('shipper_type', models.CharField(editable=False, max_length=40, verbose_name='Shipper type')),
                ('contr_eff_date', models.DateField(editable=False, verbose_name='Contract effective date')),
                ('contr_exp_date', models.DateField(editable=False, verbose_name='Contract expiration date')),
                ('logo', models.ImageField(blank=True, editable=False, null=True, upload_to='', verbose_name='Logo of the shipper')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products5_1.contact', verbose_name='Contact ID')),
            ],
            options={
                'verbose_name': 'Shipper',
                'verbose_name_plural': 'Shippers',
                'db_table': 'shippers',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateField(default='', editable=False, verbose_name='Date posted')),
                ('rating', models.FloatField(default=0, max_length=2, verbose_name='Rating')),
                ('comment', models.CharField(default='', max_length=999, verbose_name='Comment')),
                ('client_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.client', verbose_name='Client ID')),
                ('product_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.product', verbose_name='Product ID')),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.category', verbose_name='Category ID')),
                ('product_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.product', verbose_name='Product ID')),
            ],
            options={
                'verbose_name': 'Product category',
                'verbose_name_plural': 'Product categories',
                'db_table': 'products_categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.supplier', verbose_name='Supplier ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(default='', editable=False, verbose_name='Data of order')),
                ('pyment_method', models.CharField(default='', editable=False, max_length=20, verbose_name='Payment method')),
                ('delivery_method', models.CharField(default='', max_length=30, verbose_name='Delivery method')),
                ('delivery_date', models.DateField(default='', editable=False, verbose_name='Delivery date')),
                ('total_price', models.FloatField(default=0, editable=False, verbose_name='Total price')),
                ('sale_tax', models.FloatField(default=0, editable=False, verbose_name='Sale tax')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('total_discount', models.FloatField(default=0, verbose_name='Total discount')),
                ('paid', models.FloatField(default=0, editable=False, verbose_name='Paid')),
                ('transaction_status', models.CharField(default='', max_length=20, verbose_name='Transaction status')),
                ('client_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.client', verbose_name='Client ID')),
                ('shipper_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.shipper', verbose_name='Shipper ID')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='contact_id',
            field=models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.contact', verbose_name='Contact ID'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, verbose_name='Data')),
                ('item_price', models.FloatField(editable=False, verbose_name='Item price')),
                ('product_quantity', models.IntegerField(editable=False, verbose_name='Product quantity')),
                ('sub_total', models.FloatField(editable=False, verbose_name='Total spent')),
                ('sale_tax', models.FloatField(default=0, verbose_name='Sale tax')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('total_discount', models.FloatField(default=0, verbose_name='Total discount')),
                ('order_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.order', verbose_name='Order ID')),
                ('product_id', models.ForeignKey(default='', editable=False, on_delete=django.db.models.deletion.CASCADE, to='products5_1.product', verbose_name='Product ID')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
