# Generated by Django 3.1.4 on 2021-01-04 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products5_1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipper_id',
            new_name='shipper',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='productcategory',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='shipper',
            old_name='contact_id',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact_id',
            new_name='contact',
        ),
    ]
