# Generated by Django 3.1.4 on 2020-12-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products5_1', '0002_auto_20201226_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(editable=False, max_length=200, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(editable=False, max_length=25, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(editable=False, max_length=25, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(editable=False, max_length=25, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(editable=False, max_length=200, verbose_name='Product brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(editable=False, max_length=200, verbose_name='Product name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='year_of_manufacture',
            field=models.IntegerField(editable=False, verbose_name='Year of manufacture'),
        ),
    ]
