# Generated by Django 3.1.4 on 2020-12-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products5_1', '0003_auto_20201226_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='year_of_manufacture',
            field=models.IntegerField(verbose_name='Year of manufacture'),
        ),
    ]
