# Generated by Django 3.1.4 on 2020-12-30 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products5_1', '0004_auto_20201226_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='priceeee',
        ),
    ]
