# Generated by Django 3.1.4 on 2020-12-30 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products5_1', '0006_auto_20201229_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(editable=False, max_length=60, verbose_name='Last name')),
                ('nick_name', models.CharField(editable=False, max_length=60, verbose_name='Nick name')),
                ('email', models.EmailField(editable=False, max_length=60, verbose_name='Email')),
                ('password', models.CharField(editable=False, max_length=25, verbose_name='Password')),
                ('address', models.CharField(editable=False, max_length=40, verbose_name='Address')),
                ('city', models.CharField(editable=False, max_length=80, verbose_name='City')),
                ('state', models.CharField(editable=False, max_length=50, verbose_name='State')),
                ('country', models.CharField(editable=False, max_length=40, verbose_name='Country')),
                ('postal_code', models.CharField(editable=False, max_length=5, verbose_name='Postal code')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(editable=False, max_length=30, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(editable=False, max_length=999, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(editable=False, max_length=999, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(editable=False, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_brand',
            field=models.CharField(editable=False, max_length=40, verbose_name='Product brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(editable=False, max_length=50, verbose_name='Product name'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, verbose_name='Data')),
                ('pyment_method', models.CharField(editable=False, max_length=20, verbose_name='Payment method')),
                ('delivery_method', models.CharField(editable=False, max_length=30, verbose_name='Delivery method')),
                ('delivery_date', models.DateField(editable=False, verbose_name='Delivery date')),
                ('total_price', models.FloatField(editable=False, verbose_name='Total rice')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products5_1.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
    ]
