# Generated by Django 3.1.4 on 2020-12-30 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products5_1', '0007_auto_20201229_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.FloatField(editable=False, verbose_name='Total price'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, verbose_name='Data')),
                ('item_price', models.FloatField(editable=False, verbose_name='Item price')),
                ('product_quantity', models.IntegerField(editable=False, verbose_name='Product quantity')),
                ('sub_total', models.FloatField(editable=False, verbose_name='Total spent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products5_1.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products5_1.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
