# Generated by Django 3.1.4 on 2021-01-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(editable=False, max_length=60, verbose_name='First name')),
                ('last_name', models.CharField(editable=False, max_length=60, verbose_name='Last name')),
                ('email', models.EmailField(editable=False, max_length=60, verbose_name='Email')),
                ('address', models.CharField(editable=False, max_length=40, verbose_name='Address')),
                ('city', models.CharField(editable=False, max_length=80, verbose_name='City')),
                ('state', models.CharField(editable=False, max_length=50, verbose_name='State')),
                ('country', models.CharField(editable=False, max_length=40, verbose_name='Country')),
                ('postal_code', models.CharField(editable=False, max_length=5, verbose_name='Postal code')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'clients',
            },
        ),
    ]
