# Generated by Django 3.1.4 on 2021-01-06 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, verbose_name='Data')),
                ('pyment_method', models.CharField(editable=False, max_length=20, verbose_name='Payment method')),
                ('delivery_method', models.CharField(editable=False, max_length=30, verbose_name='Delivery method')),
                ('delivery_date', models.DateField(editable=False, verbose_name='Delivery date')),
                ('total_price', models.FloatField(editable=False, verbose_name='Total price')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(editable=False, verbose_name='Data')),
                ('item_price', models.FloatField(editable=False, verbose_name='Item price')),
                ('product_quantity', models.IntegerField(editable=False, verbose_name='Product quantity')),
                ('sub_total', models.FloatField(editable=False, verbose_name='Total spent')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'carts',
            },
        ),
    ]
